name: Update TV Channels

on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante me chalega
  workflow_dispatch: # Button to manually run

jobs:
  build:
    runs-on: ubuntu-latest

    # --- YE PERMISSION BLOCK ZAROORI HAI ---
    # Isse bot ko code push karne ki taakat milti hai
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        run: python update_channels.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "bot@github.com"
          git add list
          # Sirf tab commit karega jab koi change hoga
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-updated channel list" && git push)
